### ISSUE TITLE
Travis configuration

### ISSUE THREAD

**Issue by davidszanto** [davidszanto/coinkey#2]
Travis CI engedélyezése a forkolt projektre, hogy mi is kapjunk értesítést fordítás sikerességéről

**Comment by cszoolee** [comment]
ERROR: An error occured while trying to parse your .travis.yml file.

A travis.yml file javításához a node-js: követően a számokat nem kell időzőjelek közé tenni.

**Comment by cszoolee** [comment]
A buildet sikerült lefuttatni travis-on. A failurek kezelésére új ticketet hozok létre.
