### ISSUE TITLE
Sonarqube

### ISSUE THREAD

**Issue by cszoolee** [davidszanto/coinkey#7]
.

**Comment by cszoolee** [comment]
Sonarqube telepítése, és futtatása a projecten sikeresen megtörtént.
További feladat a codesmellek javítása.

**Comment by cszoolee** [comment]
lib/util.js code smells

![image](https://cloud.githubusercontent.com/assets/20969476/26155306/0a681e06-3b13-11e7-85c3-9be14a4d349f.png)

**Comment by cszoolee** [comment]
lib/coinkey.js code smells

![image](https://cloud.githubusercontent.com/assets/20969476/26155379/31c840d4-3b13-11e7-82b1-797ec5c7cf03.png)

**Comment by davidszanto** [comment]
A codesmelleket javítottam, most újra lefuttatjuk a teszteket.

**Comment by cszoolee** [comment]
A codesmellek javítása utáni eredmény:

![image](https://cloud.githubusercontent.com/assets/20969476/26160385/6851cc52-3b21-11e7-9124-cd93ba1cd111.png)

**Comment by cszoolee** [comment]
A ticketet lezárom.
